name: Github Actions Secret

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  secrets-in-github-actions:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [12]
    runs-on: ${{ matrix.os }}
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Echo out a GitHub Actions Secret to the logs
        env:
          HUNTER_PASSWORD: ${{ secrets.HUNTERTOKENPASSWORD }}
          HUNTER_TOKEN: ${{ secrets.HUNTERACCESSTOKEN }}
        if: env.HUNTERTOKENPASSWORD == 'LitSuperStu'
        run: echo "We dem boys!"