name: Github Actions Secret

on:
  push:
    branches: [ master ]
  pull_request:
    brancehs: [ master ]

jobs:
  secrets-in-github-actions:
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked: "
          echo ${{ secrets.HUNTERTOKENPASSWORD }}
          echo "Trick to echo GitHub Actions Secret: "
          echo ${{secrets.HUNTERTOKENPASSWORD }} | sed 's/./& /g'